unit CFX.UIConsts;

interface

const
  // CLASSES
  REGISTER_CLASS_NAME = 'Cods Fluent UX';
  REGISTER_CLASS_UTILS_NAME = 'CFX Utils';

  // THEME MANAGER
  ACCENT_DIFFERENTIATE_CONST = 25;

  // COMPONENTS STYLE
  FORM_FONT_NAME = 'Segoe UI';
  FORM_FONT_HEIGHT = -16;
  FORM_SMOKE_BLEND_VALUE = 150;

  LARGE_FONT_HEIGHT = -20;

  (* Composite the form with Parital Transparency *)
  FORM_COMPOSITE_COLOR = $00FF0083;

  (* Legacy, replaced by height *)
  FORM_FONT_SIZE_1 = 12;

  (* Use the ThemeManager.IconFont function to get the optimal font *)
  FORM_ICON_FONT_NAME_NEW = 'Segoe Fluent Icons';
  FORM_ICON_FONT_NAME_LEGACY = 'Segoe MDL2 Assets';

  GENERAL_ROUND = 5;
  DEFAULT_GLASSTEXT_GLOWSIZE = 0;

  FOCUS_LINE_ROUND = 8;
  FOCUS_LINE_SIZE = 2;

  LABEL_FONT_HEIGHT = 24;
  LABEL_FONT_NAME = FORM_FONT_NAME;

  SCROLLBAR_DEFAULT_SIZE = 40;

  TOOLTIP_WIDTH = 2;
  TOOLTIP_FONT_NAME = FORM_FONT_NAME;
  TOOLTIP_FONT_SIZE = 8;
  TOOLTIP_ROUND = 5;

  CHECKBOX_ICON_SIZE = 22;
  CHECKBOX_BOX_ROUND = 6;
  CHECKBOX_TEXT_SPACE = 6;

  RADIO_TEXT_SPACE = 6;

  SELECTOR_ROUND = 20;

  SLIDER_TICK_ROUND = 2;
  SLIDER_TICK_SPACING = 3;
  SLIDER_TICK_SIZE = 2;

  ICON_GREEN = 6277996;
  ICON_ICEBLUE = 14075312;
  ICON_YELLOW = 57852;
  ICON_ROSE = 10787327;

  PANEL_LINE_ROUND = 8;
  PANEL_LINE_SPACING = 10;
  PANEL_LINE_WIDTH = 8;

  HANDLE_SEPARATOR = 1;
  MINIMISE_PANEL_ROUND = 10;
  MINIMISE_PANEL_SIZE = 60;
  MINIMISE_ICON_MARGIN = 10;

  MINIMISE_COLOR_CHANGE = 5;

  EDIT_COLOR_CHANGE = 10;
  EDIT_BORDER_FADE = 15;
  EDIT_BORDER_ROUND = 10;
  EDIT_LINE_SIZE = 2;
  EDIT_EXTRA_SPACE = 5;
  EDIT_INDIC_WIDTH = 1;

  // Hint Class
  MAX_HINT_SIZE = 200;

  // TEXT
  CHECKBOX_OUTLINE = #$E003;
  CHECKBOX_SMALL = #$E004;
  CHECKBOX_CHECKED = #$E005;
  CHECKBOX_GRAYED = #$E73C;
  CHECKBOX_FILL = #$E73B;

  RADIO_FILL = #$E91F;
  RADIO_OUTLINE = #$ECCA;
  RADIO_BULLET = #$ECCC;

  SEGOE_UI_STAR = #$E734;

  TEXT_DEFAULT_GENERIC = 'Hello World';

  // POPUP MENU
  POPUP_CAPTION_DEFAULT  = 'Popup Menu';

  POPUP_SPACING_TOPBOTTOM = 5;
  POPUP_SEPARATOR_HEIGHT = 1;
  POPUP_ITEM_HEIGHT = 35;
  POPUP_DECOR_OPACITY = 15;

  POPUP_ANIMATE_SIZE = 400;
  POPUP_ANIMATE_X_SIZE = 50;
  POPUP_MINIMUM_WIDTH = 215;
  POPUP_FRACTION_SPACE = 2;

  POPUP_LINE_SPACING = 10;
  POPUP_ITEM_SPACINT = 20;

  POPUP_RADIO = #$E915;
  POPUP_CHECKMARK = #$E73E;

  POPUP_TEXT_DISABLED = $808080;

  POPUP_ITEMS_OVERLAY_DISTANCE = 10;

  POPUP_SELECTION_ROUND = 15;
  POPUP_MENU_ROUND = 30;


implementation

end.
